### ISSUE TITLE
How to use the vae module?

### ISSUE THREAD

**Issue by sunyrain** [JinYSun/DeepAcceptor#1]
Thank you for your excellent work!
I'm trying to use your vae module to generate some molecules in my domain, but I'm new to this algorithm.
Could you please tell me , what the folder "datai" & "datao" means? And what the procedure expected to be?
Thank you very much!

**Comment by JinYSun** [comment]
In order to reduce the memory usage for each generation, we split the "GEN dataset" into multiple smaller datasets stored in the datai folder. The folder "datai" & "datao" were used to input molecules in datai dataset and output generated molecules in datao dataset. I'd recommend the VAE source codes： https://github.com/aspuru-guzik-group/chemical_vae

**Comment by sunyrain** [comment]
Thank you for your kind explanation！
